refactor the reindex subsystem completely

diff --git a/do-updates b/do-updates
--- a/do-updates
+++ b/do-updates
@@ -39,11 +39,14 @@ usage () {
 	echo "   graph-yearly - generate the yearly graph files"
 }
 
-reindex() {
+html_head() {
+	if [ -z "${1}" ]
+	then
+		echo "error, INDEX variable is empty!"
+		exit 1
+	fi
 
-IDX=${WEBROOT}/index.html
-
-cat >${IDX} <<EOF
+	cat >${1} <<EOF
 <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
 <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" dir="ltr">
 	<head>
@@ -57,425 +60,148 @@ cat >${IDX} <<EOF
 	</head>
 <body>
 <p>
-	I provide multiple statistics showing the general health of this server.
+	I provide multiple statistics showing the general health of this server.<br />
 	All statistics are gathered once a minute and the charts are redrawn every 5 minutes.
-	Additionally, this page is automatically reloaded every 5 minutes.
+	Additionally, this page is automatically reloaded every 5 minutes.<br />
 </p>
 EOF
-
-echo "<p><center>" >>${IDX}
-if [ -r ${WEBROOT}/weekly.html ]
-then
-	echo "&nbsp;&nbsp;&nbsp;<a href=\"weekly.html\">Weekly stats roundup</a>&nbsp;&nbsp;&nbsp;" >>${IDX}
-fi
-if [ -r ${WEBROOT}/monthly.html ]
-then
-	echo "&nbsp;&nbsp;&nbsp;<a href=\"monthly.html\">Monthly stats roundup</a>&nbsp;&nbsp;&nbsp;" >>${IDX}
-fi
-if [ -r ${WEBROOT}/yearly.html ]
-then
-	echo "&nbsp;&nbsp;&nbsp;<a href=\"yearly.html\">Yearly stats roundup</a>&nbsp;&nbsp;&nbsp;" >>${IDX}
-fi
-echo "</center></p><hr>" >>${IDX}
-
-for i in ${PROGS}
-do
-	if [ -z "${i##*load*}" ]
-	then
-		GRAPHS=$($i debug | grep GRAPH)
-		VAR=${i%%.*}
-		GRAPH1=$(echo ${GRAPHS} | cut -f2 -d= | awk '{print $1}')
-		GRAPH2=$(echo ${GRAPHS} | cut -f3 -d= | awk '{print $1}')
-		GRAPH1=${GRAPH1##*/}
-		GRAPH2=${GRAPH2##*/}
-		echo "<h3>${VAR}</h3>" >> ${IDX}
-		echo "<p> <img src=\"${GRAPH1}\" alt="${GRAPH1}" /> </p>" >> ${IDX}
-		echo "<br />" >> ${IDX}
-		echo "<h3>${VAR}</h3>" >> ${IDX}
-		echo "<p> <img src=\"${GRAPH2}\" alt="${GRAPH2}" /> </p>" >> ${IDX}
-		
-	elif [ -z "${i##*sitestats*}" ]
-	then
-		echo "<h3>Other System Stats</h3>" >> ${IDX}
-		$i graph >> ${IDX}
-
-	elif [ -z "${i##*fping*}" ]
-	then
-		if [ -z "${PINGS}" ];
-		then
-			echo "Need IP for fping, add to PINGS variable"
-			exit 1
-		fi
-		for IP in ${PINGS}
-		do
-			GRAPHNAME=$($i debug ${IP} | grep GRAPHNAME | cut -f 2 -d= )
-			VAR=${i%%.*}
-			echo "<h3>${VAR}</h3>" >> ${IDX}
-			GRAPHNAME=${GRAPHNAME##*/}
-			echo "<p> <img src=\"${GRAPHNAME}\" alt="${GRAPHNAME}" /> </p>" >> ${IDX}
-			echo "<br />" >> ${IDX}
-		done
-	elif [ -z "${i##*webpage*}" ]
-	then
-		GRAPHNAMES=$($i debug ${IP} | grep GRAPHNAME | cut -f 2 -d= )
-		for GRAPHNAME in ${GRAPHNAMES}
-		do
-			VAR=${i%%.*}
-			echo "<h3>${VAR}</h3>" >> ${IDX}
-			GRAPHNAME=${GRAPHNAME##*/}
-			echo "<p> <img src=\"${GRAPHNAME}\" alt="${GRAPHNAME}" /> </p>" >> ${IDX}
-			echo "<br />" >> ${IDX}
-		done
-
-	else
-		GRAPHNAME=$($i debug | grep GRAPHNAME | cut -f 2 -d= )
-		VAR=${i%%.*}
-		echo "<h3>${VAR}</h3>" >> ${IDX}
-		GRAPHNAME=${GRAPHNAME##*/}
-		echo "<p> <img src=\"${GRAPHNAME}\" alt="${GRAPHNAME}" /> </p>" >> ${IDX}
-		echo "<br />" >> ${IDX}
-	fi
-done
-
-echo "<hr />"  >> ${IDX}
-echo "<p> (c) akhepcat - <a href="https://github.com/akhepcat/System-Monitor">System-Monitor Suite</a> on Github!</p>" >> ${IDX}
-echo "</body>" >> ${IDX}
-echo "</html>" >> ${IDX}
 
 }
 
-reindex_weekly() {
-
-IDX=${WEBROOT}/weekly.html
-
-cat >${IDX} <<EOF
-<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
-<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" dir="ltr">
-	<head>
-		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
-		<meta http-equiv="Content-Style-Type" content="text/css" />
-		<meta http-equiv="Refresh" content="600" />
-		<meta http-equiv="Pragma" content="no-cache" />
-		<meta http-equiv="Cache-Control" content="no-cache" />
-		<link rel="shortcut icon" href="" />
-		<title> Real time Statistics </title>
-	</head>
-<body>
-<p>
-	I provide multiple statistics showing the general health of this server.
-	All statistics are gathered once a minute and the charts are redrawn every 10 minutes.
-	Additionally, this page is automatically reloaded every 10 minutes.
-</p>
-EOF
-
-echo "<p><center>" >>${IDX}
-if [ -r ${WEBROOT}/index.html ]
-then
-	echo "&nbsp;&nbsp;&nbsp;<a href=\"index.html\">Stats roundup</a>&nbsp;&nbsp;&nbsp;" >>${IDX}
-fi
-if [ -r ${WEBROOT}/monthly.html ]
-then
-	echo "&nbsp;&nbsp;&nbsp;<a href=\"monthly.html\">Monthly stats roundup</a>&nbsp;&nbsp;&nbsp;" >>${IDX}
-fi
-if [ -r ${WEBROOT}/yearly.html ]
-then
-	echo "&nbsp;&nbsp;&nbsp;<a href=\"yearly.html\">Yearly stats roundup</a>&nbsp;&nbsp;&nbsp;" >>${IDX}
-fi
-echo "</center></p><hr>" >>${IDX}
-
-for i in ${PROGS}
-do
-	if [ -z "${i##*load*}" ]
+html_tail() {
+	if [ -z "${1}" ]
 	then
-		GRAPHS=$($i debug | grep GRAPH)
-		VAR=${i%%.*}
-		GRAPH1=$(echo ${GRAPHS} | cut -f2 -d= | awk '{print $1}')
-		GRAPH2=$(echo ${GRAPHS} | cut -f3 -d= | awk '{print $1}')
-		GRAPH1=${GRAPH1##*/}
-		GRAPH2=${GRAPH2##*/}
-		GRAPH1=${GRAPH1//.png/-week.png}
-		GRAPH2=${GRAPH2//.png/-week.png}
-		echo "<h3>${VAR}</h3>" >> ${IDX}
-		echo "<p> <img src=\"${GRAPH1}\" alt="${GRAPH1}" /> </p>" >> ${IDX}
-		echo "<br />" >> ${IDX}
-		echo "<h3>${VAR}</h3>" >> ${IDX}
-		echo "<p> <img src=\"${GRAPH2}\" alt="${GRAPH2}" /> </p>" >> ${IDX}
-		
-	elif [ -z "${i##*fping*}" ]
-	then
-		if [ -z "${PINGS}" ];
-		then
-			echo "Need IP for fping, add to PINGS variable"
-			exit 1
-		fi
-		for IP in ${PINGS}
-		do
-			GRAPHNAME=$($i debug ${IP} | grep GRAPHNAME | cut -f 2 -d= )
-			VAR=${i%%.*}
-			echo "<h3>${VAR}</h3>" >> ${IDX}
-			GRAPHNAME=${GRAPHNAME##*/}
- 			GRAPHNAME=${GRAPHNAME//.png/-week.png}
- 			echo "<p> <img src=\"${GRAPHNAME}\" alt="${GRAPHNAME}" /> </p>" >> ${IDX}
-			echo "<br />" >> ${IDX}
-		done
-	elif [ -z "${i##*webpage*}" ]
-	then
-		GRAPHNAMES=$($i debug ${IP} | grep GRAPHNAME | cut -f 2 -d= )
-		for GRAPHNAME in ${GRAPHNAMES}
-		do
-			VAR=${i%%.*}
-			echo "<h3>${VAR}</h3>" >> ${IDX}
-			GRAPHNAME=${GRAPHNAME##*/}
-			GRAPHNAME=${GRAPHNAME//.png/-week.png}
-			echo "<p> <img src=\"${GRAPHNAME}\" alt="${GRAPHNAME}" /> </p>" >> ${IDX}
-			echo "<br />" >> ${IDX}
-		done
-
-	elif [ -z "${i##*sitestats*}" ]
-	then
-		echo "<h3>Other System Stats</h3>" >> ${IDX}
-		$i graph >> ${IDX}
-
-	else
-		GRAPHNAME=$($i debug | grep GRAPHNAME | cut -f 2 -d= )
-		VAR=${i%%.*}
-		echo "<h3>${VAR}</h3>" >> ${IDX}
-		GRAPHNAME=${GRAPHNAME##*/}
-		GRAPHNAME=${GRAPHNAME//.png/-week.png}
-		echo "<p> <img src=\"${GRAPHNAME}\" alt="${GRAPHNAME}" /> </p>" >> ${IDX}
-		echo "<br />" >> ${IDX}
+		echo "error, INDEX variable is empty!"
+		exit 1
 	fi
-done
 
-echo "<hr />" >> ${IDX}
-echo "<p> (c) akhepcat - <a href="https://github.com/akhepcat/System-Monitor">System-Monitor Suite</a> on Github!</p>" >> ${IDX}
-echo "</body>" >> ${IDX}
-echo "</html>" >> ${IDX}
-
+	cat >>${1} <<EOF
+<hr />
+<p> (c) akhepcat - <a href="https://github.com/akhepcat/System-Monitor">System-Monitor Suite</a> on Github!</p>
+</body>
+</html>
+EOF
 }
 
-# -- monthly
 
-reindex_monthly() {
-
-IDX=${WEBROOT}/monthly.html
-
-cat >${IDX} <<EOF
-<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
-<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" dir="ltr">
-	<head>
-		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
-		<meta http-equiv="Content-Style-Type" content="text/css" />
-		<meta http-equiv="Refresh" content="3600" />
-		<meta http-equiv="Pragma" content="no-cache" />
-		<meta http-equiv="Cache-Control" content="no-cache" />
-		<link rel="shortcut icon" href="" />
-		<title> Real time Statistics </title>
-	</head>
-<body>
-<p>
-	I provide multiple statistics showing the general health of this server.
-	All statistics are gathered once a minute and the charts are redrawn every hour.
-	Additionally, this page is automatically reloaded every hour.
-</p>
-EOF
-
-echo "<p><center>" >>${IDX}
-if [ -r ${WEBROOT}/index.html ]
-then
-	echo "&nbsp;&nbsp;&nbsp;<a href=\"index.html\">Stats roundup</a>&nbsp;&nbsp;&nbsp;" >>${IDX}
-fi
-if [ -r ${WEBROOT}/weekly.html ]
-then
-	echo "&nbsp;&nbsp;&nbsp;<a href=\"weekly.html\">Weekly stats roundup</a>&nbsp;&nbsp;&nbsp;" >>${IDX}
-fi
-if [ -r ${WEBROOT}/yearly.html ]
-then
-	echo "&nbsp;&nbsp;&nbsp;<a href=\"yearly.html\">Yearly stats roundup</a>&nbsp;&nbsp;&nbsp;" >>${IDX}
-fi
-echo "</center></p><hr>" >>${IDX}
-
-for i in ${PROGS}
-do
-	if [ -z "${i##*load*}" ]
+reindex() {
+	# DWMY={day,week,month,year}
+	DWMY=$1
+	if [ -z "${DWMY}" ]
 	then
-		GRAPHS=$($i debug | grep GRAPH)
-		VAR=${i%%.*}
-		GRAPH1=$(echo ${GRAPHS} | cut -f2 -d= | awk '{print $1}')
-		GRAPH2=$(echo ${GRAPHS} | cut -f3 -d= | awk '{print $1}')
-		GRAPH1=${GRAPH1##*/}
-		GRAPH2=${GRAPH2##*/}
-		GRAPH1=${GRAPH1//.png/-month.png}
-		GRAPH2=${GRAPH2//.png/-month.png}
-		echo "<h3>${VAR}</h3>" >> ${IDX}
-		echo "<p> <img src=\"${GRAPH1}\" alt="${GRAPH1}" /> </p>" >> ${IDX}
-		echo "<br />" >> ${IDX}
-		echo "<h3>${VAR}</h3>" >> ${IDX}
-		echo "<p> <img src=\"${GRAPH2}\" alt="${GRAPH2}" /> </p>" >> ${IDX}
-		
-	elif [ -z "${i##*fping*}" ]
+		echo "error, DWMY variable is empty!"
+		exit 1
+	fi
+
+	if [ "${DWMY}" = "day" ]
 	then
-		if [ -z "${PINGS}" ];
-		then
-			echo "Need IP for fping, add to PINGS variable"
-			exit 1
-		fi
-		for IP in ${PINGS}
+		IDX=${WEBROOT}/index.html
+		html_head "${IDX}"
+
+		echo "<p><center>" >>${IDX}
+		# menu header
+		for HF in $(ls ${WEBROOT}/*.html | sed "s^.*${WEBROOT}/^^g; s/\.html//g;") ;
 		do
-			GRAPHNAME=$($i debug ${IP} | grep GRAPHNAME | cut -f 2 -d= )
-			VAR=${i%%.*}
-			echo "<h3>${VAR}</h3>" >> ${IDX}
-			GRAPHNAME=${GRAPHNAME##*/}
- 			GRAPHNAME=${GRAPHNAME//.png/-month.png}
- 			echo "<p> <img src=\"${GRAPHNAME}\" alt="${GRAPHNAME}" /> </p>" >> ${IDX}
-			echo "<br />" >> ${IDX}
+			if [ "${HF}" != "index" -a "${HF}" != "weekly" -a "${HF}" != "monthly" -a "${HF}" != "yearly" ]
+			then
+				echo "<a href=\"${HF}.html\">${HF}</a>&nbsp;&nbsp;&nbsp;" >> ${IDX}
+			fi
 		done
-	elif [ -z "${i##*webpage*}" ]
+		echo "<br /><br />" >>${IDX}
+	else
+		IDX="${WEBROOT}/${DWMY}ly.html"
+		html_head "${IDX}"
+		echo "<p><center>" >>${IDX}
+	fi
+
+	if [ -r ${WEBROOT}/index.html -a "${DWMY}" != "day" ]
 	then
-		GRAPHNAMES=$($i debug ${IP} | grep GRAPHNAME | cut -f 2 -d= )
-		for GRAPHNAME in ${GRAPHNAMES}
-		do
+		echo "&nbsp;&nbsp;&nbsp;<a href=\"index.html\">Stats roundup</a>&nbsp;&nbsp;&nbsp;" >>${IDX}
+	fi
+	if [ -r ${WEBROOT}/weekly.html -a "${DWMY}" != "week" ]
+	then
+		echo "&nbsp;&nbsp;&nbsp;<a href=\"weekly.html\">Weekly stats roundup</a>&nbsp;&nbsp;&nbsp;" >>${IDX}
+	fi
+	if [ -r ${WEBROOT}/monthly.html -a "${DWMY}" != "month"  ]
+	then
+		echo "&nbsp;&nbsp;&nbsp;<a href=\"monthly.html\">Monthly stats roundup</a>&nbsp;&nbsp;&nbsp;" >>${IDX}
+	fi
+	if [ -r ${WEBROOT}/yearly.html -a "${DWMY}" != "year" ]
+	then
+		echo "&nbsp;&nbsp;&nbsp;<a href=\"yearly.html\">Yearly stats roundup</a>&nbsp;&nbsp;&nbsp;" >>${IDX}
+	fi
+	echo "</center></p><hr>" >>${IDX}
+
+	if [ "${DWMY}" != "day" ]
+	then
+		DWMY="-${DWMY}"
+	else
+		DWMY=""
+	fi
+	for i in ${PROGS}
+	do
+		if [ -z "${i##*load*}" ]
+		then
+			GRAPHS=$($i debug | grep GRAPH)
+			VAR=${i%%.*}
+			GRAPH1=$(echo ${GRAPHS} | cut -f2 -d= | awk '{print $1}')
+			GRAPH2=$(echo ${GRAPHS} | cut -f3 -d= | awk '{print $1}')
+			GRAPH1=${GRAPH1##*/}
+			GRAPH2=${GRAPH2##*/}
+			GRAPH1=${GRAPH1//.png/$DWMY.png}
+			GRAPH2=${GRAPH2//.png/$DWMY.png}
+			echo "<h3>${VAR}</h3>" >> ${IDX}
+			echo "<p> <img src=\"${GRAPH1}\" alt="${GRAPH1}" /> </p>" >> ${IDX}
+			echo "<br />" >> ${IDX}
+			echo "<h3>${VAR}</h3>" >> ${IDX}
+			echo "<p> <img src=\"${GRAPH2}\" alt="${GRAPH2}" /> </p>" >> ${IDX}
+		
+		elif [ -z "${i##*sitestats*}" ]
+		then
+			echo "<h3>Other System Stats</h3>" >> ${IDX}
+			$i graph >> ${IDX}
+
+		elif [ -z "${i##*fping*}" ]
+		then
+			if [ -z "${PINGS}" ];
+			then
+				echo "Need IP for fping, add to PINGS variable"
+				exit 1
+			fi
+			for IP in ${PINGS}
+			do
+				GRAPHNAME=$($i debug ${IP} | grep GRAPHNAME | cut -f 2 -d= )
+				VAR=${i%%.*}
+				echo "<h3>${VAR}</h3>" >> ${IDX}
+				GRAPHNAME=${GRAPHNAME##*/}
+	 			GRAPHNAME=${GRAPHNAME//.png/$DWMY.png}
+	 			echo "<p> <img src=\"${GRAPHNAME}\" alt="${GRAPHNAME}" /> </p>" >> ${IDX}
+				echo "<br />" >> ${IDX}
+			done
+		elif [ -z "${i##*webpage*}" ]
+		then
+			GRAPHNAMES=$($i debug ${IP} | grep GRAPHNAME | cut -f 2 -d= )
+			for GRAPHNAME in ${GRAPHNAMES}
+			do
+				VAR=${i%%.*}
+				echo "<h3>${VAR}</h3>" >> ${IDX}
+				GRAPHNAME=${GRAPHNAME##*/}
+				GRAPHNAME=${GRAPHNAME//.png/$DWMY.png}
+				echo "<p> <img src=\"${GRAPHNAME}\" alt="${GRAPHNAME}" /> </p>" >> ${IDX}
+				echo "<br />" >> ${IDX}
+			done
+		else
+			GRAPHNAME=$($i debug | grep GRAPHNAME | cut -f 2 -d= )
 			VAR=${i%%.*}
 			echo "<h3>${VAR}</h3>" >> ${IDX}
 			GRAPHNAME=${GRAPHNAME##*/}
-			GRAPHNAME=${GRAPHNAME//.png/-month.png}
+			GRAPHNAME=${GRAPHNAME//.png/$DWMY.png}
 			echo "<p> <img src=\"${GRAPHNAME}\" alt="${GRAPHNAME}" /> </p>" >> ${IDX}
 			echo "<br />" >> ${IDX}
-		done
-
-	elif [ -z "${i##*sitestats*}" ]
-	then
-		echo "<h3>Other System Stats</h3>" >> ${IDX}
-		$i graph >> ${IDX}
-
-	else
-		GRAPHNAME=$($i debug | grep GRAPHNAME | cut -f 2 -d= )
-		VAR=${i%%.*}
-		echo "<h3>${VAR}</h3>" >> ${IDX}
-		GRAPHNAME=${GRAPHNAME##*/}
-		GRAPHNAME=${GRAPHNAME//.png/-month.png}
-		echo "<p> <img src=\"${GRAPHNAME}\" alt="${GRAPHNAME}" /> </p>" >> ${IDX}
-		echo "<br />" >> ${IDX}
-	fi
-done
-
-echo "<hr />" >> ${IDX}
-echo "<p> (c) akhepcat - <a href="https://github.com/akhepcat/System-Monitor">System-Monitor Suite</a> on Github!</p>" >> ${IDX}
-echo "</body>" >> ${IDX}
-echo "</html>" >> ${IDX}
-
-}
-
-# -- yearly
-
-reindex_yearly() {
-
-IDX=${WEBROOT}/yearly.html
-
-cat >${IDX} <<EOF
-<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
-<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" dir="ltr">
-	<head>
-		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
-		<meta http-equiv="Content-Style-Type" content="text/css" />
-		<meta http-equiv="Refresh" content="14400" />
-		<meta http-equiv="Pragma" content="no-cache" />
-		<meta http-equiv="Cache-Control" content="no-cache" />
-		<link rel="shortcut icon" href="" />
-		<title> Real time Statistics </title>
-	</head>
-<body>
-<p>
-	I provide multiple statistics showing the general health of this server.
-	All statistics are gathered once a minute and the charts are redrawn every 4 hours.
-	Additionally, this page is automatically reloaded every 4 hours.
-</p>
-EOF
-
-echo "<p><center>" >>${IDX}
-if [ -r ${WEBROOT}/index.html ]
-then
-	echo "&nbsp;&nbsp;&nbsp;<a href=\"index.html\">Stats roundup</a>&nbsp;&nbsp;&nbsp;" >>${IDX}
-fi
-if [ -r ${WEBROOT}/weekly.html ]
-then
-	echo "&nbsp;&nbsp;&nbsp;<a href=\"weekly.html\">Weekly stats roundup</a>&nbsp;&nbsp;&nbsp;" >>${IDX}
-fi
-if [ -r ${WEBROOT}/monthly.html ]
-then
-	echo "&nbsp;&nbsp;&nbsp;<a href=\"monthly.html\">Monthly stats roundup</a>&nbsp;&nbsp;&nbsp;" >>${IDX}
-fi
-echo "</center></p><hr>" >>${IDX}
-
-for i in ${PROGS}
-do
-	if [ -z "${i##*load*}" ]
-	then
-		GRAPHS=$($i debug | grep GRAPH)
-		VAR=${i%%.*}
-		GRAPH1=$(echo ${GRAPHS} | cut -f2 -d= | awk '{print $1}')
-		GRAPH2=$(echo ${GRAPHS} | cut -f3 -d= | awk '{print $1}')
-		GRAPH1=${GRAPH1##*/}
-		GRAPH2=${GRAPH2##*/}
-		GRAPH1=${GRAPH1//.png/-year.png}
-		GRAPH2=${GRAPH2//.png/-year.png}
-		echo "<h3>${VAR}</h3>" >> ${IDX}
-		echo "<p> <img src=\"${GRAPH1}\" alt="${GRAPH1}" /> </p>" >> ${IDX}
-		echo "<br />" >> ${IDX}
-		echo "<h3>${VAR}</h3>" >> ${IDX}
-		echo "<p> <img src=\"${GRAPH2}\" alt="${GRAPH2}" /> </p>" >> ${IDX}
-		
-	elif [ -z "${i##*fping*}" ]
-	then
-		if [ -z "${PINGS}" ];
-		then
-			echo "Need IP for fping, add to PINGS variable"
-			exit 1
 		fi
-		for IP in ${PINGS}
-		do
-			GRAPHNAME=$($i debug ${IP} | grep GRAPHNAME | cut -f 2 -d= )
-			VAR=${i%%.*}
-			echo "<h3>${VAR}</h3>" >> ${IDX}
-			GRAPHNAME=${GRAPHNAME##*/}
- 			GRAPHNAME=${GRAPHNAME//.png/-year.png}
- 			echo "<p> <img src=\"${GRAPHNAME}\" alt="${GRAPHNAME}" /> </p>" >> ${IDX}
-			echo "<br />" >> ${IDX}
-		done
-	elif [ -z "${i##*webpage*}" ]
-	then
-		GRAPHNAMES=$($i debug ${IP} | grep GRAPHNAME | cut -f 2 -d= )
-		for GRAPHNAME in ${GRAPHNAMES}
-		do
-			VAR=${i%%.*}
-			echo "<h3>${VAR}</h3>" >> ${IDX}
-			GRAPHNAME=${GRAPHNAME##*/}
-			GRAPHNAME=${GRAPHNAME//.png/-year.png}
-			echo "<p> <img src=\"${GRAPHNAME}\" alt="${GRAPHNAME}" /> </p>" >> ${IDX}
-			echo "<br />" >> ${IDX}
-		done
+	done
 
-	elif [ -z "${i##*sitestats*}" ]
-	then
-		echo "<h3>Other System Stats</h3>" >> ${IDX}
-		$i graph >> ${IDX}
-
-	else
-		GRAPHNAME=$($i debug | grep GRAPHNAME | cut -f 2 -d= )
-		VAR=${i%%.*}
-		echo "<h3>${VAR}</h3>" >> ${IDX}
-		GRAPHNAME=${GRAPHNAME##*/}
-		GRAPHNAME=${GRAPHNAME//.png/-year.png}
-		echo "<p> <img src=\"${GRAPHNAME}\" alt="${GRAPHNAME}" /> </p>" >> ${IDX}
-		echo "<br />" >> ${IDX}
-	fi
-done
-
-echo "<hr />" >> ${IDX}
-echo "<p> (c) akhepcat - <a href="https://github.com/akhepcat/System-Monitor">System-Monitor Suite</a> on Github!</p>"  >> ${IDX}
-echo "</body>" >> ${IDX}
-echo "</html>" >> ${IDX}
-
+	html_tail "${IDX}"
 }
 
 do_updates()
@@ -591,10 +317,10 @@ do_auto()
 
 	if [ 0 -eq $((TS % 86400)) ]
 	then
-		reindex_yearly
-		reindex_monthly
-		reindex_weekly
-		reindex
+		reindex year
+		reindex month
+		reindex week
+		reindex day
 	fi
 
 
@@ -666,13 +392,13 @@ case $CMD in
 		;;
 	(graph-yearly) do_graphs yearly
 		;;
-	(reindex) reindex
+	(reindex) reindex day
 		;;
-	(reindex-weekly) reindex_weekly
+	(reindex-weekly) reindex week
 		;;
-	(reindex-monthly) reindex_monthly
+	(reindex-monthly) reindex month
 		;;
-	(reindex-yearly) reindex_yearly
+	(reindex-yearly) reindex year
 		;;
 	(auto) do_auto
 		;;
